### ISSUE TITLE
Окно для рисования хотелось бы иметь "бесконечной площади"

### ISSUE THREAD

**Issue by vpashka** [hanadeev/lpeditor#1]
1. Окно для рисования хотелось бы иметь "бесконечной площади" 
2. Масштабирование всей схемы 
3. Возможность раздвигать (менять высоту) окна с xml-схемой 
4. Загрузка/выгрузка файла
5. Сетка и автоматическая привязка к узлам сетке
6. Выравнивание элементов между собой
7. Меню для привязки датчиков к EXT, OUT
8. Меню для настройки параметров элементов (например время в Delay)

P.S. Хотя наверно каждое замечание должно было бы быть отдельными issue

**Comment by vpashka** [comment]
Для пунктов 2...8 создал отдельные issue. Поэтому этот теперь про 
п.1 Окно для рисования хотелось бы иметь "бесконечной площади"

**Comment by hanadeev** [comment]
Решил не делать полосы прокрутки, просто как в AutoCad - бесконечное поле
